### ISSUE TITLE
Typo in Overview page

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti-doc#105]
There is a typo with the word "located", it's showing "locoated" in the Dark Services and Routers section

https://openziti.github.io/ziti/overview.html#dark-services-and-routers

**Comment by Sir-Rumeh** [comment]
I will work on this. Assign me to it please

**Comment by dovholuknf** [comment]
go for it ! :) welcome to openziti

**Comment by Sir-Rumeh** [comment]
Awesome, thanks!

I submitted a pull request for the fix yesterday.
