### ISSUE TITLE
tunnellers page overhaul

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-doc#115]
https://openziti.github.io/ziti/clients/linux.html hasn't been updated for a long time. re-read it and fix anything missing. SPECIFICALLY rework the page (if nothing else) to use/mention ziti-edge-tunnel vs ziti-tunnel

**Comment by qrkourier** [comment]
I took a pass at this a few months ago and will let the issue be closed when we accept https://github.com/openziti/ziti-doc/pull/209
