### ISSUE TITLE
PULL REQUEST:  Documentation updates for Docker-Compose installation

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti-doc#126]
Just a note that I have created a PR for some documentation updates

**Comment by gberl002** [comment]
I'm not seeing any PRs from you, can you provide a link so I can see what's going on?

**Comment by gooseleggs** [comment]
The pr was pulled in yesterday.

**Comment by dovholuknf** [comment]
Strange, I don't see any from you either. I see you had one in your fork but it was closed on the next day? Is this the PR? https://github.com/gooseleggs/ziti-doc/pull/1/files

Which PR was merged yesterday? Do you have a link to the PR? I'm curious as well

**Comment by qrkourier** [comment]
Sounds like it's taken care of. Re-open this if not.
