### ISSUE TITLE
Some Notes are not rendering properly

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti-doc#128]
There are two "Notes" in the following doc page that are not rendering as graphical notes in the deployed doc.

Please deploy locally to confirm the fix is working, using a generic markdown renderer won't render them properly, they will likely appear fixed when they are not actually fixed.

Source file:
`docfx_project/ziti/quickstarts/zac/installation.md`

Rendered output (look for `> [!Note] >` followed by some text and `<`):
https://openziti.github.io/ziti/quickstarts/zac/installation.html#using-docker-compose

**Comment by cnu1812** [comment]
This issue is resolved. can close this

**Comment by dovholuknf** [comment]
Thanks again!
