### ISSUE TITLE
Addition to documentation.

### ISSUE THREAD

**Issue by cnu1812** [openziti/ziti-doc#134]
It would be great if you explain or give an example of what script to execute here. In readme.md file.
![Screenshot 2022-07-06 115131](https://user-images.githubusercontent.com/75531528/177482898-52ca58c8-eff7-47f7-9753-0cb7ac69282c.png)

**Comment by dovholuknf** [comment]
Hi @cnu1812 thanks for this issue!  That's definitely a really fantastic idea. I'm surprised it's not called out. I'll fix this.
