### ISSUE TITLE
update/remove example configs

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-doc#152]
https://openziti.github.io/ziti/manage/sample-controller-config.yaml
https://openziti.github.io/ziti/manage/sample-edge-router-config.yaml

found under the manage menu are very much out of date. either update them with one that the quickstart generates, remove the nodes, or fix the doc correctly
 
![image](https://user-images.githubusercontent.com/46322585/185517514-907d4a5b-e3db-4344-8f50-d42640e10aab.png)

**Comment by cnu1812** [comment]
Here is the example configuration file link https://github.com/openziti/ziti/blob/release-next/etc/ctrl.with.edge.yml, but I'm not finding this file in this repo.

**Comment by dovholuknf** [comment]
right now, when the `./gendoc.sh` script runs, part of that script will go out and clone sub-repos. the /ziti repo is one of those repos. In this repo you'll find that node by running this from the root:
```
grep "Configuration File Example" -r docfx_project/ziti
docfx_project/ziti/manage/toc.yml:  - name: Configuration File Example
docfx_project/ziti/manage/toc.yml:    - name: Configuration File Example
docfx_project/ziti/manage/toc.yml:#    - name: Configuration File Example
```
so the `docfx_project/ziti/manage/toc.yml` file contains this entry....

Now to complicate matters, I'm actively (as in it's what i'm working on right now) in the midst of moving our docs away from docfx and into docusaurus. You can find that new site currently under /docusaurus of the main site: https://openziti.github.io/docusaurus

In ** that ** site i've not replicated these nodes, so... in a way i've already fixed this particular issue too. :( I've not closed this issue yet, since I've not moved us over to docusaurs yet... 

So - if you want to fix this for hacktoberfest - i would accept it :) it's not labeled as hacktoberfest yet but I could take care of all that.  

Hope that all makes sense. Thanks for checking out the issue list! We appreciate the 👀 :)

**Comment by cnu1812** [comment]
You are moving this project to docusaurus wow. I'm gonna involve in this from now. And would like to contribute to this repo https://openziti.github.io/docusaurus .

**Comment by dovholuknf** [comment]
i haven't updated the readme.md yet, but you can pull and checkout the main branch. after doing that you should run `./gendoc.sh -cd` to pull down all the dependencies (if you don't you'll get a build warning when running docusaurus)

After that, you can `cd docusaurus` and run `yarn start` to fire up the site and see it locally. lmk if you have questions.

**Comment by dovholuknf** [comment]
oh and if you're going to make any changes - make sure you run `yarn build` before putting a PR up to make sure it all works properly :)

**Comment by cnu1812** [comment]
Thank you @dovholuknf for explaining this. I too have some experience working with docusaurus. So ig I'll make it!

**Comment by cnu1812** [comment]
hi @dovholuknf , I noticed that sidebar is similar for all the nav bar items.
![Screenshot 2022-09-29 092308](https://user-images.githubusercontent.com/75531528/192935061-8c381cf1-682b-4f6e-a4e6-14cd264c5323.png)
Is there any thought on changing that, if so I would like to work on that? Thank You!

**Comment by dovholuknf** [comment]
It's a very rough work in progress right now that I'm working on this week. I have been trying to keep the sidebar auto generated to make contributions easier. I plan to reorganize it, it's getting a bit large.

What sort of changes were you thinking?

**Comment by cnu1812** [comment]
> It's a very rough work in progress right now that I'm working on this week. I have been trying to keep the sidebar auto generated to make contributions easier. I plan to reorganize it, it's getting a bit large.
> 
> What sort of changes were you thinking?

like we have currently and removing getting started and replace with articles

**Comment by dovholuknf** [comment]
I am sorry but I can't seem to have the same vision in my head that you're proposing. If you could mock it up, maybe I could understand better. It might be worthwhile to wait a couple of days though since I'm very active in there right now.

My goal is to simply present the material in as clear a way possible. I feel like there's some organization of terms that will need to happen. I feel like the sidebar has too many top level items.

**Comment by dovholuknf** [comment]
i've had to remove the nodes today - sorry @cnu1812 , they were getting referenced by users. I've removed them from the doc site. thanks for looking at this issue though. the docusaurus merge for docs will be soon.
