### ISSUE TITLE
document standard configs

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-doc#160]
Need examples and explanation of the five standard config types. This will inform users of `ziti` CLI and ZEDS could link back to this new documentation. ZED services are currently a dead end for the user if they don't have prior knowledge how to compose a standard config. We should prominently feature the two most common standard config types with multiple examples: `host.v1`, `intercept.v1` and list the most relevant variables that apply to each e.g. `$dst_hostname`, `$tunneler_id.name`.

**Comment by qrkourier** [comment]
This doc has some examples with variables https://github.com/netfoundry/MEC/tree/master/Azure/PublicMEC#readme

**Comment by mytlogos** [comment]
Can you reopen the issue?
The current documented standard configs are host.v1 and host.v2.
The documentation for intercept.v1 is still missing?

https://openziti.io/docs/reference/config-types/
