### ISSUE TITLE
update overview image

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-doc#162]
somehow this image:

![image](https://openziti.github.io/images/ziti-overview.svg)

says "local computer network"... change that to just 'network' or 'internet' or anything not 'local'

**Comment by cnu1812** [comment]
Could you please send the working path for this issue?

**Comment by dovholuknf** [comment]
oh - sorry, i actually fixed this just the other day and forgot to close this issue! :( closing now, it now says 'internet'
