### ISSUE TITLE
update doc to specify ziti-console needs newer node versions

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-doc#173]
Recently an upgrade forces the version of node to be newer.  Cloud VMs/ubuntu ship with 'comparatively old' versions of node. Ziti Console needs node LTS (16+). Update the docs to indicate what that looks like and why

**Comment by Areadrill** [comment]
Hi. Can I be assigned to this issue?

**Comment by dovholuknf** [comment]
Hi @Areadrill - sure it can! This is what the doc looks like right now: https://openziti.github.io/ziti/quickstarts/zac/installation.html

This is the file that needs to be updated: https://github.com/openziti/ziti-doc/blob/main/docfx_project/ziti/quickstarts/zac/installation.md

I'd like to see on there that per the package.json you need to be running node >=14.17 (see https://github.com/openziti/ziti-console/blob/3d56cb216fe64959d9b709b15c52fee41355c503/package.json#L39-L41)

The doc should have some sort of callout - that "if you see an error like this - you probably have an older version of node.  check your node version and make sure it's recent" ... or something like that

**Comment by Areadrill** [comment]
I haven't been able to set up `ziti-console`  since I'm kind of busy with my job. Can you give me an idea of what the error is when you have an inadequate node version?
