### ISSUE TITLE
docusaurus rewrite: old docfx links

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-doc#182]
When we merge the docusaurus docs down, we'll want to make sure all/as many links as possible are redirected accordingly. Stating with the top 20. I think once we get through the top 50, we can probably consider this 'done for now' and merge and work on the other links in a separate issue

|Page   title and screen classPage title and screen classarrow_drop_down | Page path and screen classPage   path and screen classarrow_drop_down | Views|
|--- | --- | ---|
|Get Started - Build a Network! \| Ziti | / | 2,594|
|Overview \| Ziti | /ziti/overview.html | 1,713|
|Start Cooking With Ziti \| Ziti | /ziti/quickstarts/quickstart-overview.html | 614|
|Get Started - Build a Network! \| Ziti | /index.html | 582|
|Local - No Docker \| Ziti | /ziti/quickstarts/network/local-no-docker.html | 430|
|Host OpenZiti Anywhere \| Ziti | /ziti/quickstarts/network/hosted.html | 391|
|Choosing a client \| Ziti | /ziti/clients/which-client.html | 380|
|Tunnelers \| Ziti | /ziti/clients/tunneler.html | 298|
|Ziti Services \| Ziti | /ziti/services/overview.html | 284|
|Ziti Identities \| Ziti | /ziti/identities/overview.html | 280|
|Enable Prometheus to Scrape Anything from Anywhere \| Ziti | /articles/zitification/prometheus/part1.html | 264|
|Local - With Docker \| Ziti | /ziti/quickstarts/network/local-with-docker.html | 252|
|Software Architecture \| Ziti | /ziti/software-architecture.html | 252|
|\| Ziti | /api/index.html | 226|
|Local - Docker Compose \| Ziti | /ziti/quickstarts/network/local-docker-compose.html | 210|
|Starting With Services \| Ziti | /ziti/quickstarts/services/index.html | 139|
|Configuration \| Ziti | /ziti/config-store/overview.html | 127|
|Articles \| Ziti | /articles/index.html | 123|
|Installing Ziti Administration Console \| Ziti | /ziti/quickstarts/zac/installation.html | 122|
|Linux \| Ziti | /ziti/clients/linux.html | 120|
|Overview \| Ziti | /ziti/security/overview.html | 119|
|Your First Service - Zero Trust Host Access \| Ziti | /ziti/quickstarts/services/host-access.html | 99|
|Glossary \| Ziti | /glossary/glossary.html | 79|
|Ziti Controller \| Ziti | /ziti/manage/controller.html | 75|
|Ziti controlller REST API \| Ziti | /api/rest/index.html | 74|
|Creating an Identity \| Ziti | /ziti/identities/creating.html | 74|
|Hardware Security Modules (HSM) - PKCS11 \| Ziti | /ziti/quickstarts/hsm-overview.html | 72|
|Ziti SDKs \| Ziti | /ziti/clients/sdks.html | 69|
|SoftHSMv2 \| Ziti | /ziti/quickstarts/hsm/softhsm.html | 69|
|Enrolling an Identity \| Ziti | /ziti/identities/enrolling.html | 68|
|Kubernetes Sidecar Client \| Ziti | /ziti-cmd/quickstart/kubernetes/sidecar-tunnel/kubernetes-sidecar-tunnel-quickstart.html | 68|
|Policies \| Ziti | /ziti/security/authorization/policies/overview.html | 61|
|Managing Ziti \| Ziti | /ziti/manage/manage.html | 59|
|Edge Router \| Ziti | /ziti/manage/edge-router.html | 54|
|Creating a Service \| Ziti | /ziti/services/creating.html | 51|
|C SDK \| Ziti | /api/clang/index.html | 47|
|Authentication \| Ziti | /ziti/security/authentication/authentication.html | 40|
|Golang Aha! Moments \| Ziti | /articles/golang-aha/article.html | 38|
|Ziti Router \| Ziti | /ziti/manage/router-overview.html | 37|
|Ziti Metrics \| Ziti | /ziti/metrics/overview.html | 33|
|Namespace NetFoundry \| Ziti | /api/csharp/NetFoundry.html | 32|
|Zitifying SSH \| Ziti | /articles/zitification/zitifying-ssh/index.html | 32|
|Windows \| Ziti | /ziti/clients/windows.html | 29|
|Managing Configurations \| Ziti | /ziti/config-store/managing.html | 28|
|Ziti Android Quickstart \| Ziti | /ziti-android-app/README.html | 28|
|Bootstrapping Trust \| Ziti | /articles/bootstrapping-trust/part-01.encryption-everywhere.html | 26|
|Zitifying Kubectl \| Ziti | /articles/zitification/kubernetes/index.html | 22|
|Building the Ziti C SDK and Sample Apps for arm (BeagleBone)   \| Ziti | /articles/c-sdk-on-beaglebone.html | 21|
|Public Key Infrastructure (PKI) \| Ziti | /ziti/manage/pki.html | 21|
|3rd Party CA \| Ziti | /ziti/security/authentication/third-party-cas.html | 21|
|Configuring OpenZiti to Enable Prometheus \| Ziti | /articles/zitification/prometheus/part2.html | 20|
|Authorization \| Ziti | /ziti/security/authorization/authorization.html | 19|
|Scraping Anything, Anywhere in Action \| Ziti | /articles/zitification/prometheus/part3.html | 17|
|Android \| Ziti | /ziti/clients/android.html | 16|
|MacOS \| Ziti | /ziti/clients/macos.html | 16|
|Consuming Configuration Data \| Ziti | /ziti/config-store/consuming.html | 16|
|YubiKey by Yubico \| Ziti | /ziti/quickstarts/hsm/yubikey.html | 16|
|Zitification \| Ziti | /articles/zitification/index.html | 15|
|iOS \| Ziti | /ziti/clients/iOS.html | 15|
|Ziti Related Downloads \| Ziti | /ziti/downloads/overview.html | 15|
|Class ZitiConnection \| Ziti | /api/csharp/NetFoundry.ZitiConnection.html | 14|
|Prometheus Endpoint \| Ziti | /ziti/metrics/prometheus.html | 14|
|Posture Checks \| Ziti | /ziti/security/authorization/posture-checks.html | 13|
|Enrollment \| Ziti | /ziti/security/enrollment/enrollment.html | 13|
|Bootstrapping Trust \| Ziti | /articles/bootstrapping-trust/part-05.bootstrapping-trust.html | 12|
|Ziti SDKs \| Ziti | /ziti/clients/sdks | 12|
|Authentication Policies \| Ziti | /ziti/security/authentication/authentication-policies.html | 12|
|Creating an Edge Router Policy \| Ziti | /ziti/security/authorization/policies/creating-edge-router-policies.html | 11|
|Class ZitiIdentity \| Ziti | /api/csharp/NetFoundry.ZitiIdentity.html | 10|
|Zitifying SCP \| Ziti | /articles/zitification/zitifying-scp/index.html | 10|
|Troubleshooting \| Ziti | /ziti/manage/troubleshooting.html | 10|
|External JWT Signers \| Ziti | /ziti/security/authentication/external-jwt-signers.html | 10|
|Class Ziti \| Ziti | /api/csharp/NetFoundry.Ziti.html | 9|
|Delegate ZitiConnection.OnConnected \| Ziti | /api/csharp/NetFoundry.ZitiConnection.OnConnected.html | 9|
|Types of Metrics Reported \| Ziti | /ziti/metrics/metric-types.html | 9|
|Creating a Service Policy \| Ziti | /ziti/security/authorization/policies/creating-service-edge-router-policies.html | 9|
|Swift (with Objective-C interoperability) \| Ziti | /api/swift/index.html | 8|
|Certificate Management \| Ziti | /ziti/security/authentication/certificate-management.html | 8|
|MFA TOTP \| Ziti | /ziti/security/authentication/totp.html | 8|
|Delegate ZitiConnection.OnDataReceived \| Ziti | /api/csharp/NetFoundry.ZitiConnection.OnDataReceived.html | 7|
|Bootstrapping Trust \| Ziti | /articles/bootstrapping-trust/part-02.a-primer-on-public-key-cryptography.html | 7|
|\| Ziti | /ziti/ | 7|
|Identities \| Ziti | /ziti/security/authentication/identities.html | 7|
|Delegate ZitiConnection.OnDataWritten \| Ziti | /api/csharp/NetFoundry.ZitiConnection.OnDataWritten.html | 6|
|Tunnelers \| Ziti | /ziti/clients/tunneler | 6|
|API Session Certificates \| Ziti | /ziti/security/authentication/api-session-certificates.html | 6|
|Bootstrapping Trust \| Ziti | /articles/bootstrapping-trust/part-04.certificate-authorities-and-chains-of-trust.html | 5|
|Creating a Service Policy \| Ziti | /ziti/security/authorization/policies/creating-service-policies.html | 5|
|Class ZitiException \| Ziti | /api/csharp/NetFoundry.ZitiException.html | 4|
|Class ZitiStream \| Ziti | /api/csharp/NetFoundry.ZitiStream.html | 4|
|Bootstrapping Trust \| Ziti | /articles/bootstrapping-trust/part-03.certificates.html | 4|
|Edge APIs \| Ziti | /ziti/apis/edge-apis.html | 3|
|Configuration \| Ziti | /ziti/config-store/overview | 3|
|File Reporter \| Ziti | /ziti/metrics/file.html | 3|
|On Demand \| Ziti | /ziti/metrics/inspect.html | 3|
|Enum ZitiStatus \| Ziti | /api/csharp/NetFoundry.ZitiStatus.html | 2|

**Comment by qrkourier** [comment]
The redirects are active in [this preview site](https://ziti-pvbfpvu8b-openziti.vercel.app/).
