### ISSUE TITLE
Docusaurus search

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-doc#192]
I didn't find a way to search the Docusaurus site. Maybe there's a plugin we can use for that.

**Comment by dovholuknf** [comment]
it's very clearly documented on the docusaurus site what/how to do it https://docusaurus.io/docs/search


it's 100% on 'the list' - thanks for adding this issue

**Comment by qrkourier** [comment]
Algolia snippet was added in https://github.com/openziti/ziti-doc/pull/204. I'm working on getting the index populated with crawler records.

**Comment by qrkourier** [comment]
I've populated the Algolia index by running the self-hosted crawler like this:

```bash
docker run -it --env-file=.env -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper
```

with config.json:

```json
{
  "index_name": "prod_DOCUSAURUS",
  "start_urls": [
    "https://openziti.github.io/"
  ],
  "selectors": {
    "lvl0": {
      "selector": "(//ul[contains(@class,'menu__list')]//a[contains(@class, 'menu__link menu__link--sublist menu__link--active')]/text() | //nav[contains(@class, 'navbar')]//a[contains(@class, 'navbar__link--active')]/text())[last()]",
      "type": "xpath",
      "global": true,
      "default_value": "Documentation"
    },
    "lvl1": "header h1",
    "lvl2": "article h2",
    "lvl3": "article h3",
    "lvl4": "article h4",
    "lvl5": "article h5, article td:first-child",
    "lvl6": "article h6",
    "text": "article p, article li, article td:last-child"
  },
  "strip_chars": " .,;:#",
  "custom_settings": {
    "separatorsToIndex": "_",
    "attributesForFaceting": [
      "language",
      "version",
      "type",
      "docusaurus_tag"
    ],
    "attributesToRetrieve": [
      "hierarchy",
      "content",
      "anchor",
      "url",
      "url_without_anchor",
      "type"
    ]
  }
}
```

and .env file defining `APPLICATION_ID` and `API_KEY`.

**Comment by dovholuknf** [comment]
this seems like the kind of comment that should be preserved in a markdown maybe?

**Comment by qrkourier** [comment]
[Legacy Algolia scraper's Docusaurus2 sample config](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json)

**Comment by qrkourier** [comment]
I added a page in https://github.com/openziti/ziti-doc/pull/227 to document how search works. The new page will be published at https://openziti.github.io/about-search/
