### ISSUE TITLE
footer updates

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-doc#208]
the footer needs to be updated with 'whatever' we want down there. if anything else?

**Comment by qrkourier** [comment]
Added multi-column footer links starting with policies, e.g. CoC

**Comment by dovholuknf** [comment]
the footer is still a barren wasteland and also does not contain socials/links/others

**Comment by qrkourier** [comment]
Happy to add more stuff. How about these?
* duplicate social, etc. links from nav links dropdown and top-nav icons
* blog site (also add blog to nav links dropdown?)
