### ISSUE TITLE
Some API docs nav links broken

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-doc#222]
The sidebar nav links in API docs section for csharp and swift get 404 when deployed to GH Pages. The sidebar links are working with `yarn serve` so there must be some difference with GH Pages.

We can't see this problem in Vercel because when we deploy to Vercel we don't build the companion microsites in _remotes that provide this content. We would need to find a way to install Doxygen, an executable used to build the C SDK docs, in the Vercel build env and change the Vercel build command to stop sending the `-l` option to `./gendoc.sh`.

**Comment by dovholuknf** [comment]
but the C SDK still work? that's most likely because csharp and swift are now 'child' pages, deployed by their respective repo where C SDK is not. so there's something 'interesting' going on

**Comment by qrkourier** [comment]
Right, /api/clang is still working before this change.

**Comment by qrkourier** [comment]
Now swift and csharp companion sites are working even though the change from relative to absolute links hasn't merged yet.
