### ISSUE TITLE
ZEDS "read the ZEDS docs" links here to OpenZiti docs, but there's no ZEDS docs

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-doc#233]
We need a ZEDS docs page for ZEDS to link to, or ZEDS needs a microsite of its own, possibly both in that order. Currently the ZEDS app links directly to the old index.html page https://openziti.github.io/index.html, but there are no search hits for "zeds".

**Comment by smilindave26** [comment]
We could start first with a NF blog post or zendesk article that describes what it is, how to get started. (It's sandbox environment that is provided to help developers use the Ziti SDKs to embed secure connectivity in their apps.  It comes pre-configured with test services, and allows you to build more advanced services and configurations specific to your application's needs.)

**Comment by qrkourier** [comment]
It could be something like [this example for the Py echo sample](https://openziti.discourse.group/t/how-to-generate-jwt-and-json-in-ziti-for-python-sample-ziti-echo-server/1235/3?u=qrkourier).

**Comment by qrkourier** [comment]
We don't seem to be promoting ZEDS anymore.
