### ISSUE TITLE
Service Creation Docs are pointing Ziti Edge Developer Edition

### ISSUE THREAD

**Issue by emoscardini** [openziti/ziti-doc#239]
The Service Creation Page:
https://openziti.github.io/docs/core-concepts/services/creating

Has references to "Ziti Edge - Developer Edition", but it's deprecated & no longer maintained.

**Comment by smilindave26** [comment]
It’s not deprecated. We plan to add its functionality into CloudZiti, but in the mean time we are pushing SDK users to use it for development and learning. When we have the capability available in CloudZiti we’ll look at deprecating ZEDS.

**Comment by dovholuknf** [comment]
Eesh - it's even worse. that whole page needs to be rewritten. I'm removing that whole page. It's all out of date. Thanks!
