### ISSUE TITLE
miniziti still has a ziti binary dependency

### ISSUE THREAD

**Issue by sabedevops** [openziti/ziti-doc#682]
There is a single remaining `ziti edge` command in the `miniziti.bash` script. Replacing this line with `ziti_wrapper()` invocations completely eliminates any dependency of having `ziti` on the host.

**Comment by qrkourier** [comment]
Not sure if same invocation of `ziti` CLI, but `miniziti.bash login` gets:

```
+ minikube kubectl --profile miniziti -- --context miniziti get secrets ziti-controller-admin-secret --namespace miniziti --output 'go-template={{index .data "admin-password" | base64decode }}'
+ xargs ziti edge login --cli-identity miniziti --yes --username admin --password
Enter controller host[:port] (default localhost:1280): error: EOF
```

**Comment by sabedevops** [comment]
Yes, correct. This happens because when we moved the ziti binary to the container, we never login on the host. We don't currently store enough state to do this after the first run, unless we inspect the coredns configmap to find the ingress zone. I wanted to discuss this with you this morning, and was part of why I was trying to address a few other issues, but decided to wait to a more opportune time. 90/90 rule, sadly.

**Comment by sabedevops** [comment]
To be clear, there is another ziti edge command in the start path of the stack.
