### ISSUE TITLE
Docker Quickstart Failure to Write/Read Configuration File

### ISSUE THREAD

**Issue by camotts** [openziti/ziti-doc#69]
Steps:

Follow quickstart guide: https://openziti.github.io/ziti/quickstarts/network/local-with-docker.html
On the step of running the docker run command it attempts to write a file, then read a second file. Neither files exist despite logged as created.

![image](https://user-images.githubusercontent.com/14876890/152855338-bb3f446e-f69e-45a5-a1fb-a6dcc9e243bc.png)

**Comment by camotts** [comment]
Sure thing!

Edition: Windows 10 Education
Version: 21H2
Build: 19044.1466

Docker Desktop Version: 4.4.4 (73704) using WSL2 Subsystem (Windows Subsystem for Linux)

Manual Docker Process:
```
#Pull Image
docker pull openziti/quickstart:latest

#Create Network
docker network create ziti

#Run Controller
docker run --network ziti --network-alias ziti-controller --network-alias ziti-edge-controller -p 1280:1280 -it --rm -v C:\Programming\NetFoundry\ZitiExample\mountpt:/openziti/pki openziti/quickstart /openziti/scripts/run-controller.sh
```

Docker-Compose
I used the default compose and env files. No changes made.
```
#Start Compose
docker-compose --project-name docker up
```

**Comment by dovholuknf** [comment]
happily - this is not a 'windows thing'. I've pushed another docker image could you give it another try?

**Comment by dovholuknf** [comment]
should be closed with the latest docker image. please reopen if not
