### ISSUE TITLE
Create a service using CLI has incorrect syntax

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti-doc#78]
The "Create a service" section explaining how to do so in CLI uses incorrect syntax (I assume old)

Source: docfx_project/ziti/services/create-service-cli.md
Url: https://openziti.github.io/ziti/services/overview.html?tabs=create-service-cli

One example is:
`ziti edge controller create service ssh`

Whereas the actual syntax should be:
`ziti edge create service ssh`

**Comment by qrkourier** [comment]
Resolved by https://github.com/openziti/ziti-doc/pull/324
