### ISSUE TITLE
Grammatical error in Service Configuration Overview

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti-doc#91]
Missing `have` in sentence on Service Configuration overview.

> Different applications can their own configuration for the same service

**Comment by valxntine** [comment]
I'd like to pick this up if possible? I'm afk right now but can get to it tomorrow?

**Comment by BalliAsghar** [comment]
Fixed see the pull request.
#92

**Comment by dovholuknf** [comment]
Thanks @BalliAsghar

**Comment by dovholuknf** [comment]
@valxntine - thanks for the offer. Happy to have any other contributions you look to make :)
