### ISSUE TITLE
lsof requirements

### ISSUE THREAD

**Issue by za** [openziti/ziti-doc#949]
Hi there,

it seems, we're missing out one of the requirements to install openziti: `lsof`.

```
$  source /dev/stdin <<< "$(wget -qO- https://get.openziti.io/ziti-cli-functions.sh)"; expressInstall

-------------------------------------------------------------
                          _   _     _
                    ____ (_) | |_  (_)
                   |_  / | | | __| | |
                    / /  | | | |_  | |
                   /___| |_|  \__| |_|

-------------------------------------------------------------

You're missing one or more commands that are used in this script.
Please ensure the commands listed are on the path and then try again.

* lsof

```

**Comment by qrkourier** [comment]
The solution is to first install the dependencies. In this case, you must install `lsof` before running `expressInstall`.

I recommend checking out the new quickstart. Just run `ziti edge quickstart`! You can download/install from: https://openziti.io/docs/downloads/. There's also a Docker version of the quickstart in https://github.com/openziti/ziti/blob/v1.2.1/quickstart/docker/all-in-one/README.md
