### ISSUE TITLE
Quick Fix - extra accent character in quickstart doc

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti-doc#95]
There is an extra character in a sample command that will cause the command to not work if it is copied along with the command.

In Quickstart Local there is a command referenced as follows
**`"${ZITI_BIN_DIR-}/ziti" edge list edge-routers**

Just need that extra accent removed from the beginning of the command. I know, it probably took longer to create this issue but it's a good way for someone to get their name in on a code fix on an open source project.

**Comment by grlcodr** [comment]
Could I pick this one up? First time contributing to open source 😄

**Comment by dovholuknf** [comment]
Sure you can. We appreciate any and all contributions. Toss a PR up. 😃

**Comment by gberl002** [comment]
Fixed by @grlcodr in PR https://github.com/openziti/ziti-doc/pull/99
