### ISSUE TITLE
state prerequisites for expressInstall in non-Docker quickstarts

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti-doc#96]
jq is required for `expressInstall` and the install does check for this but it would be nice to enhance the part of the "Local - No Docker" install where it says jq is required so the user can install jq before watching quickstart fail because the prereq is not met.

Possibly explain how to check if it is (maybe a `which jq` or`jq --version`. Then also have a link to the jq install page in case it isn't installed.

**Comment by qrkourier** [comment]
I see what you mean about "the install does check for this" in https://github.com/openziti/ziti/blob/main/quickstart/docker/image/ziti-cli-functions.sh#L278, and I see it's `curl` too, not just `jq`, that's needed by `expressInstall`. I think you just want the web page to state that these are needed before running `expressInstall`, right?

**Comment by dovholuknf** [comment]
the pages where it's relevant do state this. See:
https://openziti.github.io/docs/quickstarts/network/local-no-docker/#one-liner-setup
https://openziti.github.io/docs/quickstarts/network/hosted#prerequisites

The "host it anywhere" quickstart does a much better job of showing this by calling it a prerequisite and using a "NOTE" block. Really, we should just update the "host it locally" to look like " host it anywhere" and the helper cli script should verify both commands are on the path before running. I think I saw a PR about testing for curl?

**Comment by dovholuknf** [comment]
also I noticed that we call the "host it anywhere" as "hosted" but i think that could probably become "anywhere" instead?

**Comment by qrkourier** [comment]
@dovholuknf incorporated your feedback in the PR linked to this issue: https://github.com/openziti/ziti-doc/pull/323
