### ISSUE TITLE
Inform user of quickstart stop commands

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti-doc#97]
The "Local - No Docker" quickstart explains how there are two commands for starting up your controller `startZitiController` and router `startExpressEdgeRouter` but doesn't mention that there are also simple commands already sourced that will stop the processes. Those would be `stopZitiController` and `stopAllEdgeRouters`

It would be nice to add a section explaining that these commands are already provided by the express install, no need to find and kill the processes manually.

**Comment by qrkourier** [comment]
Resolved by https://github.com/openziti/ziti-doc/pull/325
