### ISSUE TITLE
npm express package required for zac

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti-doc#98]
I'm not sure if this is a Mac specific thing but when I had first run the command to start up the ZAC server, I was presented with a failure that explained the `express` package was required.

After a simple `npm install express` and retrying to start ZAC everything worked.

We should verify if this is a widespread issue or just a local issue in this one case. If it's a widespread issue then update the doc to explain that this package is needed. Or maybe just add a blurb that it's needed and might not be installed and show how to install it.

**Comment by qrkourier** [comment]
This is handled by the `npm install` command in the ZAC quickstart.
https://openziti.github.io/search/?q=zac
